version: '3.9'

services:
    node_user_service:
      build:
        context: ./back-end_node
        dockerfile: user_service/Dockerfile
      ports:
        - "8000:8000"
      hostname: user-service
      networks:
        - app_net 

    node_amenity_service:
      build:
        context: ./back-end_node
        dockerfile: amenity_service/Dockerfile
      ports:
        - "8001:8001"
      hostname: amenity-service
      environment:
        - USER_AMENITY_SERVICE_URL=http://user-amenity-service:8002/api/user_amenities/
      networks:
        - app_net  

    node_user_amenity_service:
      build:
        context: ./back-end_node
        dockerfile: user_amenity_service/Dockerfile
      ports:
        - "8002:8002"
      environment:
        - USER_AMENITY_SERVICE_URL=http://user-amenity-service:8002/api/user_amenities/
      hostname: user-amenity-service
      networks:
        - app_net

    frontend:
      build: ./front-end
      ports:
        - "5173:5173"
      depends_on:
        - middleware
      networks:
        - app_net

    middleware:
      build: ./middleware
      ports:
        - "8080:8080"
      environment:
        - USER_SERVICE_URL=http://user-service:8000
        - AMENITY_SERVICE_URL=http://amenity-service:8001
        - USER_AMENITY_SERVICE_URL=http://user-amenity-service:8002
      depends_on:
        - node_user_service
        - node_amenity_service
        - node_user_amenity_service
      networks:
        - app_net
        

networks:
    app_net:
      driver: bridge